// AUTO-GENERATED: German, drawable Skribbl words.
// Sourced from a large community skribbl.io German word list (aseemrb/skribbl),
// cleaned + de-duplicated. Regenerate rather than editing by hand.

export const SKRIBBL_WORDS: string[] = [
  "ABBA", "Abend", "Abendessen", "Abfall", "Abflussrohr", "Abgrund", "abheben", "Abonnement",
  "Abraham Lincoln", "Abschleppwagen", "Abschluss", "Absperrband", "abstrakt", "Abzug", "Achsel", "Achselhöhle",
  "Achteck", "Achterbahn", "Addition", "Adidas", "Adler", "Äffchen", "Affe", "Afrika",
  "Afrofrisur", "Ägypten", "Ahorn", "Airbag", "Akkordeon", "Akne", "Aktion", "Aladdin",
  "Alarm", "Albatros", "Albtraum", "Alkohol", "Allee", "Allergie", "Alligator", "Alpaka",
  "Alphorn", "alt", "älter", "Altglascontainer", "Altweibersommer", "Alufolie", "Amboss", "Ameise",
  "Ameisenbär", "Ameisenhaufen", "Amerika", "Amor", "Ampel", "Ampelmännchen", "Amsel", "Amsterdam",
  "Anakonda", "Ananas", "Android", "Anfänger", "Anführer", "Angebot", "Angelina Jolie", "Angestellter",
  "Anglerfisch", "angreifen", "Angry Birds", "Anhalter", "Anhänger", "Anhängerkupplung", "Animation", "Anime",
  "Anker", "Antarktis", "Antilope", "Antivirus", "Anubis", "Anwalt", "Anzeige", "anzeigen",
  "Anzug", "anzünden", "Apfel", "Apfelkern", "Apfelkuchen", "Apfelsaft", "Apokalypse", "Apotheker",
  "applaudieren", "Apple", "Aprikose", "Aquarium", "Äquator", "arbeiten", "Arbeiter", "Arbeitszimmer",
  "Archäologe", "Architekt", "Argentinien", "Aristokrat", "Arm", "Armaturenbrett", "Armband", "Armbanduhr",
  "Armbrust", "Ärmel", "Armleuchter", "Artist", "Arzt", "Arztkoffer", "Asche", "Aschenbecher",
  "Asien", "Ass", "Ast", "Asterix", "Asteroid", "Astronaut", "asymmetrisch", "Atem",
  "Athlet", "Atlantis", "atmen", "Atmosphäre", "Atom", "Atombombe", "Atomuhr", "Aubergine",
  "Audi", "Aufhänger", "Aufkleber", "Aufnahme", "aufnehmen", "aufwachen", "aufwerten", "Aufzug",
  "Auge", "Augenbinde", "Augenbraue", "Augenlid", "Auspuff", "ausruhen", "Außerirdischer", "Aussichtspunkt",
  "Auster", "Australien", "Autogramm", "Autor", "Autoradio", "Avocado", "axe", "Axolotl",
  "Axt", "Baby", "backen", "Backenzahn", "Bäcker", "Bäckerei", "Badeanzug", "Badekappe",
  "Bademantel", "Badewanne", "Badezimmer", "Bagel", "Bagger", "Baguette", "Bahnschiene", "Bajonett",
  "Baklava", "Balkon", "Ball", "Ballett", "Ballon", "Bambi", "Bambus", "Banane",
  "Band", "Bandnudel", "Bandscheibenvorfall", "Banjo", "Bank", "Bankier", "Bar", "Bär",
  "Barack Obama", "Barbar", "Barbecue", "Barbier", "Barcode", "Bärenfalle", "Bargeld", "Barkeeper",
  "Bart", "Bart Simpson", "Baseballschläger", "Basis", "Basketball", "Batman", "Batterie", "Bauarbeiter",
  "Bauch", "Bauchnabel", "bauchpinseln", "Bauer", "Bauernhof", "Baum", "Baumhaus", "Baumkrone",
  "Baumkuchen", "Baumstumpf", "Baumwolle", "Bayern", "Beatbox", "Becken", "Bedienung", "Beerdigung",
  "Beethoven", "befehlen", "Befehlshaber", "Beförderung", "begrüßen", "behindert", "Beine", "beißen",
  "beizen", "bekifft", "Belgien", "Benachrichtigung", "Benzin", "Berg", "Bergkette", "Berlin",
  "Bernstein", "berühmt", "Berühmtheit", "berühren", "Besen", "Besenstiel", "Bestatter", "Bestrafung",
  "besuchen", "beten", "betrügen", "Bett", "Bettdecke", "Bettwanze", "Beule", "Beute",
  "bezaubernd", "Beziehung", "Bibel", "Biber", "Bibliothekar", "biegen", "Biene", "Bienenkönigin",
  "Bienenstich", "Bienenstock", "Bier", "Big Ben", "Bikini", "Bildhauer", "Bildschirm", "Bill Gates",
  "Billard", "binden", "Bingo", "Biologie", "Biotonne", "Birke", "Birne", "Biss",
  "Bitcoin", "Black Friday", "Blase", "Blasebalg", "Blatt", "blau", "Blaubeere", "Bleiche",
  "bleichen", "Bleistift", "blind", "Blitz", "blood", "Blume", "Blumenkohl", "Blumenstrauß",
  "Blut", "Blüte", "Blutegel", "Bluterguss", "Blutspende", "BMW", "BMX", "Bob",
  "Bob Ross", "Bock", "Bodybuilding", "Bogen", "Bogenschütze", "Bohne", "Bohnenstange", "Böller",
  "Bombe", "Bomberman", "Bonbon", "Bongo", "book", "Boot", "Boris Becker", "Bösewicht",
  "Bowling", "Box", "Boxer", "Brasilien", "Brathering", "Bratsche", "Brause", "Braut",
  "Bräutigam", "Brecheisen", "Brennnessel", "Brett", "Brezel", "Briefkasten", "Brieföffner", "Brieftaube",
  "Briefträger", "Brille", "Brocken", "Brokkoli", "Bronze", "Brot", "Brownie", "Bruce Lee",
  "Bruch", "Brücke", "brüllen", "brünett", "Brunnen", "Brust", "Brusthaare", "Brustkorb",
  "Buch", "Bücherei", "Bücherregal", "Bücherwurm", "Bügeleisen", "Bugs Bunny", "Bühne", "Bullauge",
  "Bulldozer", "Bulle", "Bumerang", "Bungee Jumping", "Buntstift", "Bürgermeister", "Bürgersteig", "Burgruine",
  "Büro", "Büroklammer", "Burrito", "Bürste", "Bus", "Busch", "Busfahrer", "Bushaltestelle",
  "Butter", "Cajon", "Camping", "Cappuccino", "Captain America", "Cartoon", "Cat Woman", "cell",
  "Cello", "Cerberus", "Chamäleon", "Champagner", "Champagnersorbet", "Champion", "chaotisch", "Charlie Chaplin",
  "Chat", "Cheerleader", "Cheeseburger", "Chef", "chemisch", "Chewbacca", "Chihuahua", "China",
  "Chinatown", "Chinchilla", "Chinesische Mauer", "Chips", "Chirurg", "Christbaumkugel", "Chrome", "Chuck Norris",
  "ClickBait", "Clown", "Clownfisch", "Cockpit", "Cocktail", "Coffeeshop", "Cola", "Comic",
  "Comicbuch", "Community", "compass", "Computer", "cone", "copy", "Corn Dog", "Corn Flakes",
  "Cousin", "Cowboy", "Crash Bandicoot", "Creeper", "Creme", "Croissant", "Cupcake", "Curry",
  "Cyborg", "Dach", "Dachboden", "Dachfenster", "Dachs", "Dachschaden", "Daffy Duck", "Dalmatiner",
  "Dämon", "Dampf", "Dänemark", "Darm", "Darsteller", "Darts", "Darwin", "Dattel",
  "Daumen", "Daune", "Deadpool", "Decke", "Deckenventilator", "Degen", "Delfin", "Delle",
  "Demonstration", "denken", "Deodorant", "depressiv", "Der Rosarote Panther", "Desoxyribonukleinsäure", "Dessert", "Detektiv",
  "detonieren", "Deutschland", "Dexter", "Diagonale", "Diagramm", "Diamant", "Diät", "Didgeridoo",
  "Dieb", "Diener", "Dienstag", "differenzieren", "Dikdik", "Dinosaurier", "Diplom", "Dirndl",
  "Discord", "Diskette", "Distanz", "Diva", "DNS", "Doktor", "Dolch", "Dollar",
  "Domino", "Dompteur", "Donald Duck", "Donald Trump", "Döner", "Donner", "Donnerstag", "Donut",
  "doppelt", "Dora", "Dorf", "Doritos", "Dose", "Dosenöffner", "Drache", "Dracula",
  "Drama", "draußen", "Dreck", "dreckig", "drehen", "Dreieck", "Dreirad", "Drillinge",
  "drinnen", "Drucker", "Dschungel", "Dudelsack", "Duell", "Dumbo", "Düne", "dünn",
  "dürr", "Dürre", "Durst", "Dusche", "Dynamit", "Dynamo", "E-Gitarre", "Eber",
  "Echo", "Ecke", "eclipse", "Edelstein", "Efeu", "Ehefrau", "Ehemann", "Ei",
  "Eiche", "Eichel", "Eichhörnchen", "Eidechse", "Eierbecher", "Eierschachtel", "Eiffelturm", "Eigelb",
  "Eimer", "Einbahnstraße", "Eingabestift", "Einhorn", "Einhornwal", "einkaufen", "Einkaufswagen", "Einkaufszentrum",
  "Einrad", "Einschlag", "Einschränkung", "Einsiedler", "Einstein", "Eintopf", "Einzelhandel", "Eis",
  "Eis am Stiel", "Eisbär", "Eisberg", "Eisen", "Eiskaffee", "Eistee", "Eisverkäufer", "Eiszapfen",
  "Elch", "Elefant", "Elektriker", "elektrisch", "Elektroauto", "Elektron", "Elfenbein", "Ellbogen",
  "Elmo", "Elon Musk", "Elsa", "Elster", "Eltern", "Eminem", "Emoji", "Emu",
  "Ende", "Engel", "England", "Ente", "Entensuppe", "epilieren", "erbrechen", "Erbsen",
  "Erdbeben", "Erdbeere", "Erde", "Erdkern", "Erdmännchen", "Erdnuss", "Erdnuss-flips", "Erfindung",
  "erfrieren", "Erfrierung", "erinnern", "Erkältung", "ernten", "erröten", "erschreckend", "erzählen",
  "Esel", "Eselsbrücke", "Eselsohr", "Espresso", "Essen", "Essig", "Essiggurke", "Essstäbchen",
  "Etagenbett", "Eule", "Euro", "Europa", "Euter", "Evolution", "Excalibur", "Experiment",
  "Explosion", "fabelhaft", "Fabrik", "Facebook", "Fächer", "Fackel", "Fahnenstange", "Fahrbahn",
  "fahren", "Fahrer", "Fahrkarte", "Fahrrad", "Fahrwerk", "Falle", "fallen", "Fallschirm",
  "Falltür", "falsche Zähne", "Falte", "falten", "Familie", "Family Guy", "Fanta", "Farbe",
  "farbenblind", "Farbpalette", "Farn", "Fass", "Fassade", "Fässchen", "Fastfood", "Fata Morgana",
  "Faultier", "Faustkampf", "Fechten", "Feder", "Federball", "Federmäppchen", "Fee", "Fehler",
  "Feierabend", "feiern", "Feld", "Feldstecher", "Fell", "Felsen", "Fenster", "Fensterbank",
  "Ferien", "Ferkel", "Fernbedienung", "Fernglas", "fernsehen", "Fernseher", "Fernsehturm", "Ferrari",
  "Ferse", "Festival", "Festung", "Feueralarm", "Feuerball", "feuerfest", "Feuersalamander", "Feuerwache",
  "Feuerwehrauto", "Feuerwehrmann", "Feuerwerk", "Feuerzeug", "Fidget Spinner", "Figur", "Film", "Filmemacher",
  "Filmriss", "Filter", "Finger", "Fingerhut", "Fingernagel", "Fingerpuppe", "Fingerspitze", "Finn",
  "Finn und Jake", "Finnland", "Fisch", "Fischer", "Fischernetz", "Fischgräte", "Fitness Trainer", "flach",
  "Flagge", "Flamingo", "Flammenwerfer", "Flammkuchen", "Flasche", "Flaschendrehen", "Flaschenöffner", "Flaschenpost",
  "Flash", "flashlight", "Fledermaus", "Fleisch", "Fleischbällchen", "fleischfressend", "Fliege", "fliegen",
  "fliegendes Schwein", "Fliegenklatsche", "Fliegenpilz", "Flipper", "Floh", "Flohmarkt", "Florida", "Florist",
  "Floß", "Flöte", "Flügel", "Flughafen", "Flugzeug", "Fluss", "flüssig", "flüstern",
  "Flutlicht", "Föhn", "föhnen", "Form", "Fossil", "Fotograf", "Frankenstein", "Frankreich",
  "Fred Feuerstein", "Freddie Faulig", "frei schweben", "Freibad", "Freiheitsstatue", "Freitag", "Frieden", "Friedhof",
  "Frisbee", "Friseur", "Fritten", "Frosch", "Frost", "Frucht", "Frühling", "Frühlingsrolle",
  "Frühstück", "Fuchs", "Fühler", "Funke", "funkeln", "Fuß", "Fußball", "Fussel",
  "Fußende", "Gabel", "gähnen", "Galaxie", "Gandalf", "Gandhi", "Gang", "Gangster",
  "Gans", "Gänseblümchen", "Garage", "Garfield", "Garnele", "Garten", "Gärtner", "Gas",
  "Gasmaske", "Gasse", "Gazelle", "Gebäck", "Gebäude", "Gebiss", "Gebrauchtwagenhändler", "gebrochenes Herz",
  "Geburtstag", "geduldig", "Gefahr", "Gefängnis", "Gefrierschrank", "gehen", "Gehirn", "Gehirnwäsche",
  "gehorchen", "Geier", "Geige", "Geist", "geizig", "Gekritzel", "gelangweilt", "gelb",
  "Geld", "Geldbeutel", "Gelee", "Gemüse", "gemütlich", "genau", "Generator", "Genie",
  "Gentleman", "Geografie", "Geologe", "Gepäck", "Gepäckträger", "Gepard", "Geröll", "Geschäft",
  "Geschenk", "Geschirrschrank", "Geschlecht", "Gesicht", "Gesichtsbemalung", "gestresst", "Gesundheit", "Getränk",
  "Gewalt", "Gewinner", "Gewitter", "Gewürz", "Geysir", "Gier", "Gießkanne", "Gift",
  "giftig", "Giftzwerg", "Gipfelkreuz", "Gips", "Giraffe", "Gitarre", "Gitter", "Gladiator",
  "Glanz", "Glas", "glass", "Glatze", "Gleichgewicht", "Glitzer", "Globus", "Glocke",
  "Glockenspiel", "Glück", "glücklich", "Glücksrad", "Glücksspiel", "Glühbirne", "glühen", "Glühwürmchen",
  "Glut", "Gnom", "Goblin", "Gold", "goldener Apfel", "goldenes Ei", "Goldfisch", "Goldkette",
  "Goldtopf", "Golf", "Golfwagen", "Gong", "Goofy", "googeln", "Google", "Gorilla",
  "Gott", "Götterspeise", "Gottesanbeterin", "Gourmet", "Grab", "graben", "Grabmal", "Grabstein",
  "Graffiti", "Grafik", "Grafiktablett", "Granatapfel", "Granate", "Grapefruit", "Gras", "Grashüpfer",
  "Green Lantern", "Grenze", "Griechenland", "Grill", "Grille", "Grillen", "Grinch", "Grinsen",
  "Grippe", "Groschen", "Großmutter", "Grotte", "Gru", "Grubenarbeiter", "grün", "Guillotine",
  "Gully", "Gumball", "Gummi", "Gummibärchen", "Gummiwürmchen", "Gurke", "Gürtel", "Gürteltier",
  "gut", "Gymnastik", "Haare", "Haarfarbe", "haarig", "Haarschnitt", "Haarschuppen", "Haarspange",
  "Haarspray", "Hackbraten", "Hacker", "Hafen", "Hafenbecken", "Hagel", "Hahn", "Hähnchen",
  "Hai", "Haken", "Halbinsel", "Halbkreis", "Halbleiter", "Hälfte", "Hals", "Halskette",
  "Halskrause", "Haltestelle", "Hamburger", "Hammer", "Hammerhai", "Hampelmann", "Hamster", "Hand",
  "Handfläche", "Handgelenk", "Handschlag", "Handschuh", "Handtuch", "Handy", "Hängebauchschwein", "Hängebrücke",
  "Hängematte", "Happy Meal", "Harfe", "Harpune", "Harry Potter", "hart", "Harz", "Hase",
  "Haselnuss", "Hashtag", "Haus", "Hausmeister", "Hausnummer", "Haut", "Hawaii", "Hawaiihemd",
  "Hecht", "Heckspoiler", "Heiligenschein", "Heinzelmännchen", "heiß", "Heiße Schokolade", "Heizungskessel", "Held",
  "Helikopter", "Helium", "Hello Kitty", "Helm", "Henne", "Herbst", "Herde", "Herkules",
  "herunterladen", "Herz", "Heuschrecke", "Hexe", "Hieroglyphen", "High Five", "High Heels", "High Score",
  "Himbeere", "Himmel", "Himmelbett", "Hip Hop", "Hippie", "Hirsch", "Hitze", "Hobbit",
  "Hochzeit", "Hochzeitskutsche", "Hockey", "Höhle", "Höhlenforscher", "Höhlenmensch", "Hölle", "Hollywood",
  "Hologramm", "Holz", "Holzfäller", "Holzscheit", "Homer Simpson", "Honig", "Honigwabe", "Horizont",
  "Horn", "Hose", "Hosenstall", "Hosentasche", "Hotdog", "Hotel", "Huf", "Hügel",
  "Huhn", "Hühnchen", "Hula Hoop", "Hulk", "Hummer", "Hund", "Hundehütte", "Hunger",
  "hüpfen", "Hüpfkästchen", "Hürdenlauf", "Hut", "Hütte", "Hyäne", "Hydrant", "hypnotisieren",
  "Idee", "Igel", "Ikea", "Indianer", "Indien", "Ingenieur", "Injektion", "inkognito",
  "Inlineskates", "Insekt", "Insel", "insolvent", "Intel", "Internet", "Interview", "Inuit",
  "Invasion", "iPad", "iPhone", "Irland", "Irokesenfrisur", "Iron Giant", "Iron Man", "Island",
  "Israel", "Italien", "Jacht", "Jacke", "Jackie Chan", "Jagdziel", "jagen", "Jäger",
  "Jaguar", "Jahrbuch", "Jahreszeit", "Jalapeno", "James Bond", "Japan", "Jay Z", "Jazz",
  "Jeans", "Jeep", "Jenga", "Jesus", "Jesus Christ", "Jetski", "Jimmy Neutron", "Jo-Jo",
  "Joghurt", "John Cena", "John Lennon", "Johnny Bravo", "jonglieren", "Journalist", "jung", "Junge",
  "Junk Food", "Jupiter", "Kabel", "kabellos", "Kabine", "Käfer", "Kaffee", "Käfig",
  "kahl", "Kakao", "Kakerlake", "Kaktus", "Kalender", "kalt", "Kaltwachsstreifen", "Kamel",
  "Kamera", "Kameramann", "Kamin", "Kamm", "Kanada", "Kanalisation", "Kanarienvogel", "Känguru",
  "Kanister", "Kanone", "Kapitän", "Kappe", "Karaoke", "Karate", "Karneval", "Karotte",
  "Karte", "Karteikasten", "Kartoffel", "Kartoffelbrei", "Kartoffelpuffer", "Karussell", "Käse", "Käsekuchen",
  "Kasino", "Kastagnetten", "Kastanie", "Katalog", "Katamaran", "Katana", "Katapult", "Katastrophe",
  "Kathedrale", "Katy Perry", "Kätzchen", "Katze", "Katzenklo", "kauen", "Kaugummi", "Kaugummikugel",
  "Kaulquappe", "Kaviar", "Kazoo", "Kebab", "Kegel", "Kegelrobbe", "Kehle", "Keim",
  "Keks", "Keksdose", "Keller", "Kellner", "Kendama", "Kennzeichen", "Kermit", "Kernkraftwerk",
  "Kernspintomografie", "Kerze", "Kerzenleuchter", "Kerzenständer", "Kessel", "Ketchup", "Kette", "Kettenkarussell",
  "Kettensäge", "keuchen", "Keyboard", "KFC", "Kiefer", "kiffen", "Killerwal", "Kim Jong-Un",
  "Kim Kardashian", "Kind", "Kindergarten", "Kinderwagen", "King Kong", "Kinn", "Kino", "Kirby",
  "Kirche", "Kirschblüte", "Kirsche", "Kissen", "Kissenschlacht", "Kiste", "Kitesurfen", "kitzeln",
  "Kiwi", "Klarinette", "Klassenzimmer", "klatschen", "Klaue", "Klavier", "Klaviersaite", "Klebeband",
  "Kleber", "Klebestift", "klebrig", "Kleeblatt", "Kleid", "Kleiderbügel", "Kleinbus", "kleiner Finger",
  "Klempner", "klettern", "Klimaanlage", "Klingelton", "klingen", "Klippe", "Klobrille", "Knallfrosch",
  "Knast", "Kneipe", "Knie", "knien", "Knoblauch", "Knöchel", "Knopf", "Knoten",
  "Koala", "Kobra", "Koch", "kochen", "Köcher", "Köder", "Koffer", "Kohle",
  "Kohlrübe", "Kojote", "Kokon", "Kokosnuss", "Kolibri", "Kolosseum", "Komet", "Komiker",
  "Kommunismus", "Komödie", "Kompass", "Kondenswasser", "Konfetti", "König", "König der Löwen", "Königin",
  "königlich", "Konsole", "Kontinent", "Kontrabass", "Konversation", "Konzert", "Kopf", "Kopfende",
  "Kopfhörer", "Kopflaus", "Kopfschmerzen", "Kopftuch", "Kopie", "kopieren", "Koralle", "Korallenriff",
  "Korb", "Korken", "Korkenzieher", "Krabbe", "Krähe", "Krake", "krank", "Krankenhaus",
  "Krankenschwester", "Krankenwagen", "Krankheit", "Kranz", "kratzen", "Krawatte", "Krebs", "Kredit",
  "Kredithai", "Kreditkarte", "Kreide", "Kreis", "Kreuzfahrt", "Kreuzotter", "Kreuzung", "kriechen",
  "Kriegsschiff", "Kristall", "Kroatien", "Krokodil", "Kronkorken", "Kronleuchter", "Kröte", "Krug",
  "Krümelmonster", "Kruste", "Kuba", "Küche", "Kuchen", "Küchentuch", "Kuckuck", "Kuckucksuhr",
  "Kugelfisch", "Kuh", "Kuhglocke", "Kühlschrank", "Kunde", "Kung Fu", "Kupfer", "Kuppel",
  "Kürbis", "Kürbislaterne", "kurz", "Kurzschluss", "küssen", "Küste", "Küstenwache", "Laboratorium",
  "Labyrinth", "lächeln", "lachen", "Lachs", "Ladebalken", "Ladegerät", "laden", "Lady",
  "Lady Gaga", "Lagerfeuer", "Lagerhaus", "Lakritz", "Laktoseintoleranz", "Lama", "Lamm", "Lampe",
  "Lampenschirm", "Land", "Landschaft", "langsam", "Lanze", "Laptop", "Las Vegas", "Lasagne",
  "Laser", "Lasso", "Laterne", "Laubhaufen", "Laubsäge", "laufen", "Läufer", "Lautsprecher",
  "Lautstärke", "Lava", "Lavalampe", "Lavendel", "Lebensmittel", "Lebkuchen", "Lebkuchenhaus", "Leck",
  "Leder", "Lederhose", "Lego", "Lehm", "Lehrer", "Leiche", "Leichtsinn", "Leidenschaft",
  "Leine", "Leiter", "Leiterbahn", "Leiterwagen", "Lemur", "Leonardo da Vinci", "Leonardo DiCaprio", "lernen",
  "lesen", "Lesezeichen", "Leuchtreklame", "Leuchtstab", "Leuchtturm", "Lexikon", "Liane", "Libelle",
  "Lichtschalter", "Lichtschwert", "Lidschatten", "Liebe", "Liechtenstein", "Lieferung", "Lilie", "Limbo",
  "Limette", "Limonade", "Limousine", "Lineal", "Linie", "Link", "links", "Linse",
  "Lippen", "Lippenstift", "Lisa Simpson", "Litfaßsäule", "Litschi", "LKW", "LKW-Fahrer", "Locher",
  "Lockenwickler", "Löffel", "Logo", "London", "London Eye", "Looping", "Lorbeeren", "Lotterie",
  "Löwe", "Löwenzahn", "Luchs", "Lüfter", "Luftkissenboot", "Luftmatratze", "Luftschiff", "Luftschloss",
  "Lüftung", "Luigi", "Lunge", "Lupe", "lustig", "Lutscher", "Luxemburg", "machomäßig",
  "Madagaskar", "Mädchen", "Mafia", "Magazin", "magersüchtig", "Magie", "Magier", "Magma",
  "Magnet", "Mähdrescher", "Mahlzeit", "Maibaum", "Maikäfer", "Mais", "Maisfeld", "Maki",
  "Makkaroni", "Maler", "Malkasten", "Mammut", "Mandel", "Manege", "Maniküre", "Mantel",
  "Marathon", "Margarine", "Marge Simpson", "Marienkäfer", "Mario", "Marionette", "Mark Zuckerberg", "Marke",
  "Markt", "Marmelade", "Mars", "Marshmallow", "Maschine", "Maske", "Maskottchen", "massieren",
  "Maßstab", "Matratze", "Matrjoschka", "Matsch", "Maulkorb", "Maulwurf", "Maurer", "Maus",
  "Mäusefalle", "Mayonnaise", "McDonalds", "Mechaniker", "Medaille", "Medizin", "Medusa", "Meerenge",
  "Meeresfrüchte", "Meerjungfrau", "Meerschweinchen", "Megafon", "Meister", "Mel Gibson", "melken", "Melone",
  "Meme", "Mercedes", "Merkur", "Messer", "Metall", "Meteorit", "Meteorologe", "Mexiko",
  "Michael Jackson", "Micky Maus", "Mikrofon", "Mikroskop", "Mikrowelle", "Milch", "Milchmann", "Milchshake",
  "Milchstraße", "Militär", "Minecraft", "Mineralwasser", "Miniclip", "Minigolf", "Minion", "Minotaurus",
  "Minute", "Minze", "Mischpult", "Miss Piggy", "Mistgabel", "Mitfahrgelegenheit", "Mitternacht", "Mittwoch",
  "Mixer", "Möbel", "Modedesigner", "Model", "Mohn", "Möhre", "Mona Lisa", "Monaco",
  "Mönch", "Mond", "Monobraue", "Monster", "Mont Blanc", "Montag", "Moos", "Mopp",
  "Mörder", "Morgan Freeman", "Morgen", "Morse Code", "Morty", "Mosaik", "Moskau", "Moskito",
  "mother", "Motherboard", "Motor", "Motorrad", "Motte", "Mottenkugel", "Mount Everest", "Mount Rushmore",
  "Möwe", "Mozart", "Mr. Bean", "Mr. Meeseeks", "MTV", "Mücke", "müde", "Muffin",
  "Müllabfuhr", "Mülleimer", "Müller", "Mumie", "Mund", "Mundharmonika", "Münze", "Murmeln",
  "Murmeltier", "mürrisch", "Muschel", "Museum", "Musik", "Muskel", "Muskelkater", "Muskete",
  "Mutter", "Muttermal", "Mütze", "Nachbar", "Nachos", "Nachricht", "Nacht", "Nachtclub",
  "Nachthemd", "Nachtisch", "Nacken", "Nadel", "Nadelkissen", "Nagel", "Nagelfeile", "Nagellack",
  "Nagelpflege", "Nagelschere", "nähen", "Nähmaschine", "Nahrung", "Narbe", "Narr", "Narwal",
  "Nasa", "NASCAR", "Nase", "Nasenbluten", "Nasenhaar", "Nasenlöcher", "Nasenring", "Nashorn",
  "Natur", "Navy", "Nebel", "Nemo", "Neptun", "Nerd", "Nessie", "Nest",
  "Netz", "Netzwerk", "Neuseeland", "New York", "nichts", "Nichtschwimmer", "Nickel", "Niederlande",
  "niedlich", "niedrig", "Niere", "niesen", "Nike", "Nilpferd", "Ninja", "Nintendo",
  "Nonne", "Norden", "Nordkorea", "Nordpol", "Norwegen", "Notch", "Notenschlüssel", "Notizblock",
  "Notizbuch", "Nudel", "Nuss", "Nussknacker", "Nussschale", "Nutella", "Oase", "obdachlos",
  "Obelix", "Ober", "Oberarm", "Oberfläche", "Oberteil", "Oboe", "Observatorium", "Odysseus",
  "Ofen", "offen", "Ohr", "Ohrenschmalz", "Ohrhörer", "Ohrring", "Ohrwurm", "Oktoberfest",
  "Oktopus", "Öl", "Olaf", "Olive", "Olivenöl", "Omelett", "Onkel", "Oper",
  "Operation", "Opernhaus Sydney", "Opfer", "Orang-Utan", "Orange", "Orbit", "Orca", "Orchester",
  "Orchidee", "Ordner", "Oreo", "Organ", "Orgel", "Origami", "Oscar", "Osten",
  "Osterhase", "Ostern", "Österreich", "Otter", "Oval", "Ozean", "Pac-Man", "Paintball",
  "Palast", "palm tree", "Palme", "Panda", "Panflöte", "Panther", "Pantomime", "Panzerband",
  "Panzerfaust", "Papagei", "Papageientaucher", "Paparazzi", "Papaya", "Papier", "Papiertüte", "Pappe",
  "Paprika", "Papst", "Parade", "parallel", "Paralleluniversum", "Parfüm", "Paris", "Park",
  "Parkplatz", "Parkuhr", "Partnerlook", "Party", "Passwort", "Pasta", "Pastete", "Patenonkel",
  "Patrick Star", "Patriot", "Patrone", "Patronenhülse", "Pauke", "Pause", "Pavian", "Paypal",
  "Pech", "Pedal", "Pegasus", "Peitsche", "Pelikan", "Pendel", "Peperoni", "Peppa Pig",
  "Pepsi", "Periskop", "Perle", "Person", "Personenschützer", "Perücke", "Pfad", "Pfadfinder",
  "Pfanne", "Pfannenwender", "Pfannkuchen", "Pfau", "Pfeffer", "Pfeffersalami", "Pfeife", "pfeifen",
  "Pfeil", "Pferd", "Pferdeschwanz", "Pfirsich", "Pflaster", "Pflaume", "Pflug", "pflügen",
  "Pfote", "Pfund", "Pfütze", "Phineas und Ferb", "Photoshop", "Photosynthese", "Physalis", "Pi",
  "Picasso", "Pickel", "Picknick", "pieksen", "Pikachu", "Pilot", "Pilz", "Pinguin",
  "Pinienkerne", "pink", "Pinocchio", "Pinsel", "Pinzette", "Pirat", "Piratenschiff", "Pistazie",
  "Pistole", "Pizza", "Planet", "Planke", "Plätzchen", "Playstation", "Pluto", "Pobacken",
  "Pogo Stick", "Pokemon", "Poker", "Polarlicht", "Polizei", "Polizist", "Polo", "Pony",
  "Popcorn", "Popeye", "Portal", "Portrait", "Portugal", "Posaune", "Poseidon", "positiv",
  "Postbote", "Poster", "Postkarte", "prallen", "Präsident", "predigen", "Preisschild", "Presslufthammer",
  "Priester", "Pringles", "Prinz", "Prinzessin", "Prisma", "Professor", "Profi", "Programmierer",
  "prokrastinieren", "Propeller", "Protest", "provozieren", "Prüfung", "Psychologe", "Pu der Bär", "Publikum",
  "Pudding", "Pudel", "Puder", "Puma", "Pumba", "Punker", "Punkt", "Punkte",
  "Punktestand", "Puppe", "Puppenhaus", "Pups", "Purzelbaum", "Puzzle", "Pyramide", "Quadrat",
  "Qualle", "Quartal", "Quelle", "Querflöte", "Queue", "Rad", "Radar", "Radiergummi",
  "Radieschen", "Radio", "Radioaktivität", "Rahmen", "Rakete", "Rampe", "Rapper", "Rapunzel",
  "Rasenmäher", "Rasensprenger", "rasieren", "Rasierer", "Rasierklinge", "Rasiermesser", "Rasierschaum", "Rasseln",
  "Ratatouille", "Ratte", "Räuber", "Rauch", "rauchen", "Räucherstäbchen", "Raum", "Raumanzug",
  "Raumschiff", "Raupe", "Ravioli", "read", "Realität", "Rechen", "rechnen", "Rechnung",
  "Rechteck", "rechts", "Recycling", "Reddit", "Redner", "Reflexion", "Regal", "Regen",
  "Regenbogen", "Regenmantel", "Regenschirm", "Regentropfen", "Regenwald", "Regisseur", "Reh", "Reifen",
  "Reinheit", "reinigen", "Reinkarnation", "Reis", "Reise", "Reisender", "Reisepass", "Reißverschluss",
  "Reißverschlussverfahren", "Religion", "Rennauto", "Rennen", "Rentier", "Rentner", "reparieren", "Reptil",
  "Restaurant", "Rettich", "Rettungsring", "Rettungsweste", "Revolver", "Rezeption", "Rezeptionist", "rice",
  "Richter", "Rick", "riechen", "Riese", "Riesenrad", "Rindfleisch", "Ring", "Ringelblume",
  "Ringelschwanz", "ringen", "Rippe", "Risiko", "Ritter", "Robbe", "Robin Hood", "Roboter",
  "Rochen", "Rockstar", "Rohr", "rollen", "Roller", "Rollladen", "Rollschuhe", "Rolltreppe",
  "Rom", "Roman", "Röntgenstrahlung", "Rose", "Rosine", "Röstaroma", "rot", "Rote Beete",
  "Roter Teppich", "Rotkehlchen", "Rübe", "Rubin", "Rücken", "Rückenschmerzen", "rückgängig", "Rückgrat",
  "Rucksack", "Rückspiegel", "Ruder", "Ruhe", "Rührei", "rülpsen", "Rumänien", "Rune",
  "Russland", "Rüstung", "Rutsche", "rutschen", "rutschig", "sabbern", "Säbel", "Safari",
  "Safe", "Saft", "Saftpresse", "Säge", "Sahne", "Salami", "Salat", "salto schlagen",
  "Salz", "Salzwasser", "Samen", "Samstag", "Samsung", "Sand", "Sandalen", "Sandbank",
  "Sandburg", "Sandkasten", "Sandsturm", "Sanduhr", "Sandwich", "sanft", "Sarg", "Satellit",
  "Sattel", "Sattelschlepper", "Saturn", "Sau", "sauber", "Sauerstoff", "saufen", "Saugglocke",
  "Säule", "Sauna", "Säure", "Saxofon", "Schach", "Schacht", "Schädel", "Schaf",
  "Schal", "Schallplatte", "Schalter", "Schaltknüppel", "Schamesröte", "scharfe Soße", "Scharfschütze", "Schatten",
  "Schatz", "schauen", "Schaufel", "Schaufensterpuppe", "Schaukel", "Schaukelpferd", "Schaukelstuhl", "Schaumschläger",
  "Schauspieler", "Scheibenwelt", "Scheibenwischer", "Scheidung", "schenken", "Schere", "Scherzkeks", "Scheune",
  "Schicksal", "Schiedsrichter", "Schiefer Turm von Pisa", "schielen", "Schiffstaufe", "Schiffswrack", "Schilf", "Schimmel",
  "Schimpanse", "Schinken", "Schlacht", "Schlachter", "Schlafanzug", "schlafen", "Schlafenszeit", "Schlafstörung",
  "schlagen", "Schlagsahne", "Schlagzeug", "Schlange", "Schlauch", "schlecht", "Schleichwerbung", "Schleife",
  "Schleifpapier", "Schleim", "Schleuder", "Schlitten", "Schlittschuh", "Schlucht", "Schlumpf", "Schlüssel",
  "Schlüsselanhänger", "Schlüsselbund", "schmelzen", "Schmerz", "Schmetterling", "Schmied", "Schminke", "schminken",
  "Schnabel", "Schnabeltier", "Schnauze", "Schnecke", "Schnee", "Schneeball", "Schneeballschlacht", "Schneebesen",
  "Schneeflocke", "Schneemann", "Schneesturm", "schneiden", "schnell", "Schnellstraße", "Schnorchel", "schnorcheln",
  "Schnuller", "Schnurrbart", "Schnürsenkel", "Schock", "Schokolade", "Schornstein", "Schornsteinfeger", "Schoß",
  "Schottenrock", "Schotter", "Schottland", "Schrank", "Schranke", "Schraube", "Schraubenschlüssel", "schreiben",
  "Schreibfeder", "Schreibschrift", "Schreibtisch", "schreien", "Schriftsteller", "Schubkarre", "Schublade", "schüchtern",
  "Schuh", "Schuhkarton", "Schule", "Schulter", "Schüssel", "schütteln", "Schutzhelm", "schwach",
  "Schwalbe", "Schwamm", "Schwan", "schwanger", "Schwanz", "Schwarm", "schwarz", "Schwarzes Loch",
  "schweben", "Schweden", "Schwein", "Schweinchen Dick", "Schweinestall", "Schweiß", "Schweißer", "Schweiz",
  "Schwerkraft", "Schwert", "Schwertfisch", "Schwimmbad", "schwimmen", "schwindelig", "schwingen", "schwitzen",
  "Scooby Doo", "sea", "Sechseck", "Sechserpack", "See", "Seegurke", "Seehund", "Seeigel",
  "seekrank", "Seekuh", "Seelöwe", "Seepferdchen", "Seerose", "Seestern", "Seetang", "Seewolf",
  "Segelboot", "Segelflieger", "Segway", "Seife", "Seifenblase", "Seifenoper", "Seilrutsche", "Seilspringen",
  "Seiltänzer", "Seite", "Sekunde", "Senf", "Server", "Serviette", "Seuche", "Shampoo",
  "Sherlock Holmes", "Shrek", "Sichel", "Sicherheitsdienst", "Sicherheitsgurt", "Sicherheitsnadel", "Sicherung", "Sieg",
  "Silber", "Silberbesteck", "Silo", "Silvester", "Simon and Garfunkel", "Singapur", "singen", "sinken",
  "Sitzbank", "sitzen", "Sitzsack", "Skalpell", "Skateboard", "Skateboardfahrer", "Skelett", "Ski",
  "Skilift", "Skispringen", "Skittles", "Skorpion", "skribbl.io", "Skrillex", "skull", "Skulptur",
  "Skydiving", "Skyline", "Skype", "Slalom", "Slinky", "Smaragd", "smell", "sneeze",
  "Snoopy", "Snowboard", "Social Media", "Socken", "Sohn", "Soldat", "Sombrero", "Sommer",
  "Sommersprossen", "Songtext", "Sonic", "Sonne", "Sonnenaufgang", "Sonnenblume", "Sonnenbrand", "Sonnenbrille",
  "Sonnenfinsternis", "Sonnenschirm", "Sonnensystem", "Sonntag", "Soße", "Spaghetti", "Spaghettieis", "Spaghettimonster",
  "Spanien", "spannen", "Spargel", "Sparschwein", "Spartacus", "Spaten", "Specht", "Speck",
  "Speer", "Speichel", "Spender", "sperren", "Sphinx", "Spiderman", "Spiegel", "Spiegelei",
  "Spiel", "spielen", "Spieler", "Spielplatz", "Spielzeug", "Spieß", "Spinat", "Spinne",
  "Spion", "Spirale", "Spitzer", "Spitzhacke", "Spitzmaus", "Spongebob", "Spore", "Sport",
  "Sprache", "Sprecher", "Spritze", "Sprudel", "Sprühfarbe", "Sprungturm", "spucken", "Spule",
  "spülen", "Spüllappen", "Stacheldraht", "Stachelrochen", "Stachelschwein", "Stadion", "Staffelei", "stampfen",
  "Stangenbrot", "Star Wars", "stark", "Stativ", "Statue", "Stau", "Staudamm", "Steam",
  "stechen", "Steckdose", "Stecknadel", "Stegosaurus", "stehen", "Steigung", "Stein", "Steinbock",
  "Steinzeit", "Stempel", "Stephen Hawking", "sterben", "Stereo", "Stern", "Sternfrucht", "sternhagelvoll",
  "Steuergerät", "Steve Jobs", "Stewardess", "Stiefel", "Stinktier", "Stirn", "Stirnband", "Stoff",
  "Stoppschild", "Stoppuhr", "Stöpsel", "Storch", "stoßen", "Stoßstange", "Strahlung", "Strand",
  "Strandkorb", "Straße", "Straßenbahn", "Straßensperre", "Strauß", "Streichholz", "Streichholzschachtel", "stricken",
  "Strohhalm", "Strudel", "Strumpfhose", "Stubenhocker", "Student", "studieren", "Studio", "Stuhl",
  "Stuhlbein", "Sturm", "Sturz", "suchen", "Südafrika", "Süden", "Sudoku", "Südpol",
  "Suezkanal", "Sumo", "Sumpf", "sunglasses", "Superkraft", "Superman", "Supermarkt", "Suppe",
  "Suppenkelle", "Surfbrett", "Susan Wojcicki", "Sushi", "Süßholz raspeln", "Sweatshirt", "Symphonie", "Tabak",
  "Tablet", "Tablett", "Tablette", "Tacker", "Taco", "Tag", "Taille", "Tails",
  "Tal", "Talentshow", "Tandem", "Tank", "Tannenbaum", "Tannenzapfen", "tanzen", "Tapete",
  "Tarzan", "Tasche", "Taschenlampe", "Taschentuch", "Taser", "Tasmanischer Teufel", "Tasse", "Tastatur",
  "Tattoo", "Tau", "taub", "Taube", "Tauchen", "Tauchgang", "Tausendfüßer", "Taxi",
  "Taxifahrer", "Teddybär", "Tee", "Teekanne", "Teelicht", "Teelöffel", "Teich", "Teig",
  "Telefon", "Telefonbuch", "Telefonkabel", "Teleskop", "Teletubby", "Teller", "Temperatur", "Tennis",
  "Tennisschläger", "Tentakel", "Teppich", "Terminator", "Terrarium", "Terrasse", "Tetra Pak", "Tetris",
  "Teufel", "Text", "Textmarker", "Thaddäus Tentakel", "The Beatles", "The Rock", "Thermometer", "Thor",
  "Thron", "Thunfisch", "tief", "Tiegel", "Tierarzt", "Tierfutter", "Tierhandlung", "Tiger",
  "Tintenfisch", "Tintenpatrone", "tippen", "Tiramisu", "Tisch", "Tischdecke", "Tischplatte", "Tischtennisschläger",
  "Titanic", "Toast", "Toaster", "Tochter", "Toilette", "Tomate", "Töne", "Tonleiter",
  "Topf", "Tor", "Tornado", "Torpedo", "Torte", "Tortenheber", "tot", "Totem",
  "Totenkopf", "toter Winkel", "Tourist", "Tower Bridge", "Tragfläche", "Trainer", "trainieren", "Traktor",
  "Trampolin", "Träne", "Trauben", "Traubensaft", "Traum", "träumen", "Traumfänger", "traurig",
  "Treibsand", "Trend", "Tresorraum", "Tretmühle", "Triangel", "Triebwerk", "trinken", "Trinkgeld",
  "Trittstufe", "Trommel", "Trompete", "Tropfen", "Trophäe", "tropisch", "Trüffel", "Truhe",
  "Truthahn", "Tschechien", "Tuba", "Tukan", "Tumor", "Tunnel", "Tunnelblick", "Tupperdose",
  "Tür", "Turban", "Türkei", "Türklinke", "Turm", "Turmalin", "Türschloss", "Türsteher",
  "Türstopper", "Tweety", "Twitter", "Tyrannosaurus Rex", "U-Bahn", "U-Boot", "Überfall", "übergeben",
  "übergewichtig", "Überlebender", "Überschrift", "übersetzen", "überwintern", "Ufer", "UFO", "Uhr",
  "Ukulele", "umarmen", "Umhang", "umkehren", "Umweltverschmutzung", "undicht", "unendlich", "Unfall",
  "Uniform", "Universität", "Universum", "unsichtbar", "untergewichtig", "Untergrund", "Unterschrift", "Untersetzer",
  "Uranus", "Urknall", "Urlaub", "Usain Bolt", "USB", "Vakuum", "Vampir", "Vanille",
  "Vater", "Vatikan", "Vault boy", "Veganer", "Vegetarier", "Velociraptor", "Vene", "Venus",
  "Venusfliegenfalle", "Veranda", "Verband", "Verbrecher", "verdampfen", "vergessen", "vergrößern", "Verkehr",
  "Verkehrskontrolle", "verlassen", "verletzt", "Verlierer", "Verlies", "Vermieter", "Veröffentlichung", "Verpackung",
  "verrückt", "versagen", "verschwinden", "Versicherung", "Versicherungskaufmann", "versöhnen", "Versteck", "verteidigen",
  "vertikal", "verwirrt", "Video", "Videospiel", "Viertel", "Villa", "Vin Diesel", "Violine",
  "Virtual Reality", "Virus", "Vision", "Vitamin", "Vlogger", "Vodka", "Vogel", "Vogelbad",
  "Vogelbeere", "Vogelhaus", "Vogelscheuche", "Vogelspinne", "Vogelstrauß", "voll", "Volleyball", "Vollkornbrot",
  "Vollmond", "vollständig", "Voodoo", "Vorhang", "Vorschlaghammer", "vorspulen", "Vorstellungskraft", "Vulkan",
  "Vulkanologe", "Vuvuzela", "W-LAN", "Wachs", "wachsen", "wackeln", "Waffe", "Waffel",
  "Wahl", "wählen", "waist", "Wal", "Wald", "Waldbrand", "Wall-e", "Walnuss",
  "Walross", "Wand", "Wanderstock", "Wange", "Wanze", "warm", "Warnweste", "wart",
  "Warze", "Waschbär", "Waschbecken", "Waschbrettbauch", "Wäschespinne", "Waschlappen", "Waschmaschine", "Waschstraße",
  "Wasserfall", "Wasserfarbkasten", "Wasserhahn", "Wasserkreislauf", "Wasserpfeife", "Wasserpistole", "Wasserschildkröte", "Wattestäbchen",
  "Webseite", "Wecker", "Weide", "Weihnachten", "Weihnachtsbaum", "Weihnachtsmann", "Wein", "weinen",
  "Weinglas", "Weinrebe", "Weintrauben", "weiß", "Weizen", "Welle", "Wellensittich", "Welt",
  "Weltraum", "Werbespot", "Werbung", "Werkzeugkasten", "Werwolf", "Wespe", "Westen", "westlich",
  "Wetter", "Wetterfrosch", "Wettervorhersage", "WhatsApp", "Widder", "Widerstand", "wiederholen", "Wiesel",
  "Wildnis", "Wildschwein", "Wildwasserbahn", "William Shakespeare", "William Wallace", "Wimper", "Wind", "Windbeutel",
  "Windel", "Windmühle", "Windows", "Windrad", "Windsack", "Windschutzscheibe", "Windsurfer", "Winter",
  "Winzer", "winzig", "Wippe", "Wirbel", "Wirbelsäule", "Wissenschaft", "Wissenschaftler", "Wohlstand",
  "Wohnung", "Wohnzimmer", "Wolf", "Wolke", "Wolkenkratzer", "Wolle", "Wolverine", "Wonder Woman",
  "Wort", "Wörterbuch", "Wrestler", "Wrestling", "Wunde", "Wunderlampe", "Wunderland", "Wunschliste",
  "Würfel", "Würfelqualle", "Wurm", "Wurst", "Wurzel", "Wüste", "wütend", "Xbox",
  "Xerox", "Xylofon", "Yeti", "Yin Yang", "Yoda", "Yoshi", "Youtube", "Youtuber",
  "Zahn", "Zahnarzt", "Zahnbürste", "Zahnfee", "Zahnlücke", "Zahnpasta", "Zahnseide", "Zahnspange",
  "Zahnstein", "Zahnstocher", "Zauberer", "Zauberstab", "Zaubertrank", "Zaubertrick", "Zaun", "Zebra",
  "Zebrastreifen", "Zecke", "Zeh", "Zehnagel", "zeigen", "Zeitlupe", "Zeitmaschine", "Zeitung",
  "Zelda", "Zelle", "Zelt", "zelten", "Zement", "Zentaur", "Zeppelin", "zerreißen",
  "zerren", "zertrümmern", "Zeuge", "Zeus", "Zickzack", "Ziege", "Ziegelstein", "Ziegenbart",
  "Ziel", "Zigarette", "Zikade", "Zimmermann", "Zimmerpflanze", "Zirkel", "Zirkus", "Zirkusdirektor",
  "Zitrone", "Zitteraal", "Zombie", "Zoo", "zoomen", "Zoowärter", "Zorro", "Zucchini",
  "Zucker", "Zuckerguss", "Zuckerstange", "Zuckerwatte", "Zug", "Zugbrücke", "Zügel", "Zuma",
  "Zündschnur", "Zunge", "zupfen", "zurückspulen", "zusammenbrechen", "zusammenzucken", "Zweig", "Zwerg",
  "Zwiebel", "Zwillinge", "Zwischendecke", "Zyklop", "Zylinder", "Zypresse",
];

/** Pick a random German word to draw. */
export function pickWord(): string {
  return SKRIBBL_WORDS[Math.floor(Math.random() * SKRIBBL_WORDS.length)];
}
